version: '3.8'

services:
  backend:
    image: devopsritiks/world-time-app-backend:1.3
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: devopsritiks/world-time-app-frontend:1.3
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
